const UF = [
    { description: 'Acre', value: 'AC' },
    { description: 'Alagoas', value: 'AL' },
    { description: 'Amapá', value: 'AP' },
    { description: 'Amazonas', value: 'AM' },
    { description: 'Bahia', value: 'BA' },
    { description: 'Ceará', value: 'CE' },
    { description: 'Distrito Federal', value: 'DF' },
    { description: 'Espírito Santo', value: 'ES' },
    { description: 'Goiás', value: 'GO' },
    { description: 'Maranhão', value: 'MA' },
    { description: 'Mato Grosso', value: 'MT' },
    { description: 'Mato Grosso do Sul', value: 'MS' },
    { description: 'Minas Gerais', value: 'MG' },
    { description: 'Pará', value: 'PA' },
    { description: 'Paraíba', value: 'PB' },
    { description: 'Paraná', value: 'PR' },
    { description: 'Pernambuco', value: 'PE' },
    { description: 'Piauí', value: 'PI' },
    { description: 'Rio de Janeiro', value: 'RJ' },
    { description: 'Rio Grande do Norte', value: 'RN' },
    { description: 'Rio Grande do Sul', value: 'RS' },
    { description: 'Rondônia', value: 'RO' },
    { description: 'Roraima', value: 'RR' },
    { description: 'Santa Catarina', value: 'SC' },
    { description: 'São Paulo', value: 'SP' },
    { description: 'Sergipe', value: 'SE' },
    { description: 'Tocantins', value: 'TO' },
];

export { UF };
